version: '3.4'

services:
  net6cqrstemplate.db:
    container_name: net6cqrstemplatedb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql


  net6cqrstemplate.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=net6cqrstemplatedb;Database=dbtest;User Id=sa;Password=SwN12345678;"
    ports:
      - "80"
    depends_on:
      - net6cqrstemplate.db

